/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaform2;

import data.StationDao;
import data.TicketDao;
import entity.Station;
import entity.Ticket;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author minh
 */
public class form1 extends javax.swing.JFrame {
    StationDao stati ;
    TicketDao tickets;
    /**
     * Creates new form form1
     */
    public form1() {
        stati = new StationDao();
        tickets = new TicketDao();
        initComponents();
        selectStationGO();
        selectStationTO();
    }
    
    public void selectStationGO(){
        DefaultComboBoxModel  model = (DefaultComboBoxModel) jComboBoxDI.getModel();
        for (Station s : stati.getAll()) {
            model.addElement(s.getName());
            
        }
        jComboBoxDI.setModel(model);
    }
    public void selectStationTO(){
         DefaultComboBoxModel  model = (DefaultComboBoxModel) jComboBoxDen.getModel();
        for (Station s : stati.getAll()) {
            model.addElement(s.getName());
        }
        jComboBoxDen.setModel(model);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePickerUtil1 = new net.sourceforge.jdatepicker.util.JDatePickerUtil();
        utilDateModel1 = new net.sourceforge.jdatepicker.impl.UtilDateModel();
        utilCalendarModel1 = new net.sourceforge.jdatepicker.impl.UtilCalendarModel();
        dateComponentFormatter1 = new net.sourceforge.jdatepicker.impl.DateComponentFormatter();
        jDatePickerUtil2 = new net.sourceforge.jdatepicker.util.JDatePickerUtil();
        jDateComponentFactory1 = new net.sourceforge.jdatepicker.JDateComponentFactory();
        sqlDateModel1 = new net.sourceforge.jdatepicker.impl.SqlDateModel();
        utilDateModel2 = new net.sourceforge.jdatepicker.impl.UtilDateModel();
        jDatePickerUtil3 = new net.sourceforge.jdatepicker.util.JDatePickerUtil();
        dateComponentFormatter2 = new net.sourceforge.jdatepicker.impl.DateComponentFormatter();
        jDatePickerUtil4 = new net.sourceforge.jdatepicker.util.JDatePickerUtil();
        dateLabelFormatter1 = new org.jdatepicker.DateLabelFormatter();
        dateLabelFormatter2 = new org.jdatepicker.DateLabelFormatter();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNameKH = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jComboBoxDI = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxDen = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1Chieu = new javax.swing.JRadioButton();
        jRadioButton = new javax.swing.JRadioButton();
        jTextFieldTE = new javax.swing.JTextField();
        jDateChooserStart = new com.toedter.calendar.JDateChooser();
        jDateChooserEnd = new com.toedter.calendar.JDateChooser();
        jButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ten khach hang");

        jLabel2.setText("so dien thoai");

        jLabel3.setText("ga di");

        jTextFieldNameKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameKHActionPerformed(evt);
            }
        });

        jComboBoxDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDIActionPerformed(evt);
            }
        });

        jLabel4.setText("ga den");

        jLabel5.setText("ngay di");

        jLabel6.setText("ngay den");

        jLabel8.setText("loai ve");

        jLabel9.setText("nguoi lon");

        jLabel10.setText("tre em");

        buttonGroup1.add(jRadioButton1Chieu);
        jRadioButton1Chieu.setText("chieu");

        buttonGroup1.add(jRadioButton);
        jRadioButton.setText("khu hoi");

        jDateChooserStart.setDateFormatString("dd-MM-yyyy");
        jDateChooserStart.setMinSelectableDate(new java.util.Date(-62135791091000L));

        jDateChooserEnd.setDateFormatString("dd-MM-yyyy");

        jButtonAdd.setText("them ");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateChooserEnd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jDateChooserStart, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxDen, 0, 379, Short.MAX_VALUE)
                                .addComponent(jComboBoxDI, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPhone)
                                .addComponent(jTextFieldNameKH)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButton1Chieu)
                                    .addGap(54, 54, 54)
                                    .addComponent(jRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jTextFieldNL, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel10)
                                    .addGap(39, 39, 39)
                                    .addComponent(jTextFieldTE, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButtonAdd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNameKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooserStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooserEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton1Chieu)
                    .addComponent(jRadioButton))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButtonAdd)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void jTextFieldNameKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameKHActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldNameKHActionPerformed
//d	phone	fromS	Type	startDate	endDate	adult	fromSName	toSName	
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Ticket ticket = new Ticket();
        ticket.setPassenger(jTextFieldNameKH.getText());
        ticket.setPhone(jTextFieldPhone.getText());
        ticket.setFromSName((String) jComboBoxDI.getSelectedItem());
        ticket.setToSName((String) jComboBoxDen.getSelectedItem());
        ticket.setStartDate(sdf.format(jDateChooserStart.getDate()));
        ticket.setEndDate(sdf.format(jDateChooserEnd.getDate()));
        ticket.setType(jRadioButton.isSelected() ? 0 :1);
        //ticket.setFromS();
        ticket.setAdult(Integer.parseInt(jTextFieldNL.getText()));
        ticket.setChild(Integer.parseInt(jTextFieldTE.getText()));
        tickets.insert(ticket);
        SelecTable();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jComboBoxDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private net.sourceforge.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private net.sourceforge.jdatepicker.impl.DateComponentFormatter dateComponentFormatter2;
    private org.jdatepicker.DateLabelFormatter dateLabelFormatter1;
    private org.jdatepicker.DateLabelFormatter dateLabelFormatter2;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JComboBox<String> jComboBoxDI;
    private javax.swing.JComboBox<String> jComboBoxDen;
    private com.toedter.calendar.JDateChooser jDateChooserEnd;
    private com.toedter.calendar.JDateChooser jDateChooserStart;
    private net.sourceforge.jdatepicker.JDateComponentFactory jDateComponentFactory1;
    private net.sourceforge.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private net.sourceforge.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private net.sourceforge.jdatepicker.util.JDatePickerUtil jDatePickerUtil3;
    private net.sourceforge.jdatepicker.util.JDatePickerUtil jDatePickerUtil4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton;
    private javax.swing.JRadioButton jRadioButton1Chieu;
    private javax.swing.JTextField jTextFieldNL;
    private javax.swing.JTextField jTextFieldNameKH;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldTE;
    private net.sourceforge.jdatepicker.impl.SqlDateModel sqlDateModel1;
    private net.sourceforge.jdatepicker.impl.UtilCalendarModel utilCalendarModel1;
    private net.sourceforge.jdatepicker.impl.UtilDateModel utilDateModel1;
    private net.sourceforge.jdatepicker.impl.UtilDateModel utilDateModel2;
    // End of variables declaration//GEN-END:variables

    private void SelecTable() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
